---
- name: ensure pip.conf file is present in home directory
  become: yes
  become_user: "{{ user }}"
  lineinfile:
    path: ~/.config/pip/pip.conf
    line: "{{ item }}"
    create: yes
  with_items:
    - '[install]'
    - 'user=1'
  when: pip2_install is defined and user is defined
- name: install pip2 packages for root
  pip:
    name: "{{ pip2_install }}"
  when: pip2_install is defined and user is not defined
- name: install pip2 packages for user "{{ user }}"
  become: yes
  become_user: "{{ user }}"
  pip:
    name: "{{ pip2_install }}"
    extra_args: --user
  when: pip2_install is defined and user is defined
